apiVersion: v1
data:
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-timeout: "600"
  hsts-include-subdomains: "false"
  body-size: "750m"
  server-name-hash-bucket-size: "256"
  proxy_http_version: "1.1"
  proxy_set_header: "Upgrade $http_upgrade"
  proxy_set_header: "Connection \"upgrade\""
  proxy_set_header: "Host $host"
kind: ConfigMap
metadata:
  namespace: nginx-ingress
  name: nginx