apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: app.lightstanza.com
    http:
      paths:
      - path: /socket-test
        backend:
          serviceName: test-service
          servicePort: 80