apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8443
    protocol: TCP
  selector:
    app: app
  sessionAffinity: clientIP